# Datasource applicative VulnWatch
# Grafana 13+ : le nom de base DOIT être dans jsonData.database
apiVersion: 1

deleteDatasources:
  - name: PostgreSQL
    orgId: 1

datasources:
  - name: PostgreSQL
    uid: postgres
    type: postgres
    access: proxy
    url: postgres:5432
    user: ${POSTGRES_USER}
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    jsonData:
      sslmode: disable
      postgresVersion: 1500
      timescaledb: false
      database: ${POSTGRES_DB}
    isDefault: true
    editable: true
    version: 2
